/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Car.gltf --transform 
Files: Car.gltf [4.69MB] > Car-transformed.glb [1.8MB] (62%)
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-aventador-svj-sc20-carbon-edition-7c2ec7bcd5a94dc8a482b6a5773b5260
Title: Lamborghini Aventador SVJ - SC20 CARBON EDITION
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.CARROSSERIE} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.PaletteMaterial001} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.PaletteMaterial002} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.PaletteMaterial003} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.CARROSSERIE} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={[1.06, 1, 1]} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.Grille_2_Texture} position={[0, 0.433, -0.02]} rotation={[1.561, 0, 0]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Textured_2_Texture} position={[0, 0.433, -0.02]} rotation={[1.561, 0, 0]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.PaletteMaterial004} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.CRBN_JANTE} position={[0, -0.032, -0.015]} rotation={[-0.009, Math.PI / 2, 0]} scale={9.186} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.PaletteMaterial005} position={[0, -0.032, -0.015]} rotation={[-0.009, Math.PI / 2, 0]} scale={9.186} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.PZEO} position={[0, -0.032, -0.015]} rotation={[-0.009, Math.PI / 2, 0]} scale={9.186} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.PaletteMaterial004} position={[0.002, 0.054, -0.028]} rotation={[-0.009, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_111.geometry} material={materials['Material.069']} position={[0, -0.044, -0.015]} rotation={[-0.009, 0, 0]} scale={[1.06, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/Car-transformed.glb')
