/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Nike.gltf --transform 
Files: Nike.gltf [13.55MB] > Nike-transformed.glb [839.21KB] (94%)
Author: pandan (https://sketchfab.com/pandan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-mag-15ef47bad0aa4666b459cf78261abce5
Title: Nike Air Mag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Color } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Nike-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.StingrayPBS1SG } 
      
       position={[0, 0.232, 0.245]} rotation={[-1.826, 0, 0]} scale={0.011} />
    </group>
  )
}

useGLTF.preload('/Nike-transformed.glb')
