/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 setup.gltf --transform 
Files: setup.gltf [8.99MB] > setup-transformed.glb [347.19KB] (96%)
Author: AntonYurevich (https://sketchfab.com/antonyurevich)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-i-mac-9a6f06a783f54d9ca5087d51a63a5c42
Title: Apple I Mac
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/setup-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Apple_LP} position={[-78.066, 73.483, 11.978]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/setup-transformed.glb')
